### ISSUE TITLE
Version identifier

### ISSUE THREAD

**Issue by radarhere** [HOST-Oman/libraqm#103]
Raqm makes use of `FRIBIDI_MAJOR_VERSION` to test the Fribidi version. However, there is no version identifier in raqm to allow others to test it in turn. Are you interested in adding a version identifier to the raqm source?

**Comment by hugovk** [comment]
This would be useful for us to be able to specifically target features by version, rather than making a guess about the existence of an unrelated function (see https://github.com/python-pillow/Pillow/pull/3856#issuecomment-493683649).

If it can be added, it'd be great to release 0.7 or 0.6.1 with the contents of 0.6 plus the version number, so we can make use of it right away.

Thank you!

**Comment by khaledhosny** [comment]
For the use case above, a macro won’t help since you are checking at runtime, so you need something like `raqm_version()` as well. This still wouldn’t help your case immediately sine the new function wouldn’t be present in older versions any way. The current check is good enough, no API is going to be removed ever.

**Comment by hugovk** [comment]
> For the use case above, a macro won’t help since you are checking at runtime, so you need something like `raqm_version()` as well. 

Yes please.

> This still wouldn’t help your case immediately sine the new function wouldn’t be present in older versions any way.

Yes, that's why a 0.7 or 0.6.1 release with no other changes (except the version number) would let us target that. For the benefit clean code, it would be ok to exclude those with 0.6, and those who've already upgraded to 0.6 will likely soon upgrade to 0.6+.

> The current check is good enough, no API is going to be removed ever.

I admire your optimism :)

In any case, it would still be useful to add a version in the future, so we don't need to make assumptions about the presence of unrelated features when targeting other new features.

Thank you!

**Comment by khaledhosny** [comment]
> > The current check is good enough, no API is going to be removed ever.
> 
> I admire your optimism :)

That is not optimism, we don’t remove APIs ever. If an API becomes inadequate for some reason, it gets deprecated and a new API is introduced.

**Comment by hugovk** [comment]
Thank you for adding the version!
